---
title: Draft of possible correlations to include in paper
output:
  md_document:
    variant: markdown_github
---

```{r get_ns, echo=FALSE, message=FALSE}
library(tidyverse)
library(here)
wi <- read_csv(here("data/watershed_integrity.csv"))

count_sites <- function(ws, var, grp = quo(site)){
  x <- wi %>%
    filter(watershed==ws) %>%
    filter(variable==var) %>%
    na.omit() %>%
    group_by(!!grp) %>%
    n_groups()
    x
}

```

# Graphs of response data relationships with IWI/ICI + six functional group indices for manuscript

## Calapooia

### Nitrogen (n=`r count_sites("calapooia","logNdif")` streams):
- logNdif (nitrate) diff (annual concentration fluctuation) vs. IWI
- logNdif (nitrate) diff (annual concentration fluctuation) vs. ICI
- logNdif (nitrate) diff (annual concentration fluctuation) vs. WCHEM
- logNdif (nitrate) diff (annual concentration fluctuation) vs. CCHEM

### Isotopes (Chironomids, n=`r count_sites("calapooia","dN15chironomid")` streams):
- dN15chironomid vs. IWI
- dN15chironomid vs. ICI
- dN15chironomid vs. WCHEM
- dN15chironomid vs. CCHEM
- dN15chironomid vs. WHABT
- dN15chironomid vs. CHABT

### Watershed N budget (n=`r count_sites("calapooia","total_in")` sites) (total nitrogen (TN) input):
- total_in vs. IWI
- total_in vs. ICI
- total_in vs. WCHEM
- total_in vs. CCHEM

### Stream Physical Habitat (n=`r count_sites("calapooia","xcmgw")` streams):
- xcmgw (riparian vegetation cover (%) riparian vegetation density and complexity) vs. IWI
- xcmgw (riparian vegetation cover (%) riparian vegetation density and complexity) vs. ICI
- xcmgw (riparian vegetation cover (%) riparian vegetation density and complexity) vs. WHABT
- xcmgw (riparian vegetation cover (%) riparian vegetation density and complexity) vs. CHABT
- xembed (% sediment embeddedness) vs. IWI
- xembed (% sediment embeddedness) vs. ICI
- xembed (% sediment embeddedness) vs. WSED
- xembed (% sediment embeddedness) vs. CSED

### Fish MMI (n=`r count_sites("calapooia","fishMMI")` streams):
- Fish MMI vs. IWI
- Fish MMI vs. ICI
- Fish MMI vs. WHYD
- Fish MMI vs. CHYD
- Fish MMI vs. WHABT
- Fish MMI vs. CHABT

### Stream Temperature - Maximum Temperature (n=`r count_sites("calapooia","max_tempC_summer")` streams):
- Max Temp vs. IWI
- Max Temp vs. ICI
- Max Temp vs. WTEMP
- Max Temp vs. CTEMP

### Phase (index of Thermal Regime Timing) (n=`r count_sites("calapooia","phase")` streams)
- Phase vs. IWI
- Phase vs. ICI
- Phase vs. WTEMP
- Phase vs. CTEMP

## Choptank River

### Intersection of Streams (NHD v2) and Wetlands within catchment (n=`r count_sites("choptank","WetPercentage",quo(comid))` catchments)
- WetPercentage (% areal coverage of wetlands intersecting streams per catchment) vs. IWI
- WetPercentage (% areal coverage of wetlands intersecting streams per catchment) vs. ICI
- WetPercentage (% areal coverage of wetlands intersecting streams per catchment) vs. WCONN
- WetPercentage (% areal coverage of wetlands intersecting streams per catchment) vs. CCONN

## East Fork Little Miami River

### Nitrogen (n=`r count_sites("east fork little miami river","log10TNOxdif")` streams)
- Log10 TNoxdif (Log10 Nitrate/Nitrite annual range) vs. IWI
- Log10 TNoxdif (Log10 Nitrate/Nitrite annual range) vs. ICI
- Log10 TNoxdif (Log10 Nitrate/Nitrite annual range) vs. WCHEM
- Log10 TNoxdif (Log10 Nitrate/Nitrite annual range) vs. CCHEM
- Log10 TNoxdif (Log10 Nitrate/Nitrite annual range) vs. WSED
- Log10 TNoxdif (Log10 Nitrate/Nitrite annual range) vs. CSED

## Narragansett Bay Watershed

### Streams - Nitrogen (n=`r count_sites("narragansett bay","log10no3")` streams)
- Log10No3 (Total Nitrate (NO3) vs. IWI
- Log10No3 (Total Nitrate (NO3) vs. ICI
- Log10No3 (Total Nitrate (NO3) vs. WCHEM
- Log10No3 (Total Nitrate (NO3) vs. CCHEM

### Streams - Chloride (n=`r count_sites("narragansett bay","log10chloride")` streams)
- log10chloride Chloride vs. IWI
- log10chloride Chloride vs. ICI
- log10chloride Chloride vs. WCHEM
- log10chloride Chloride vs. CCHEM

### Streams - Isotopes (Periphyton, n=`r count_sites("narragansett bay","pN15")` streams)
- pN15 vs. IWI
- pN15 vs. ICI
- pN15 vs. WCHEM
- pN15 vs. CCHEM

### Lakes - Isotopes (Benthic Organic Matter (BOM), n=`r count_sites("narragansett bay","d15NBOM")` lakes)
- dN15BOM vs IWI
- dN15BOM vs ICI
- dN15BOM vs WCHEM
- dN15BOM vs CCHEM
