---
title: "Response Variable Summary Tables"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(stringr)
library(knitr)
```

```{r read_data, include=FALSE}
wi <- read_csv(here("data/watershed_integrity_new_2.csv"))
index_vars <- c("iwi", "ici","wchem","cchem","whabt","chabt","wsed","csed","whyd",
                "chyd","wtemp","ctemp", "wconn", "cconn")
```

# Calapooia

```{r calapooia_data, include=FALSE}
summ_cal <- wi %>%
  filter(watershed == "calapooia") %>%
  filter(!variable %in% index_vars) %>%
  filter(!stringr::str_detect(variable, "_old")) %>%
  group_by(variable) %>%
  summarise("N" = n(),
            "Minimum" = round(min(value,na.rm = T), 2),
            "Maximum" = round(max(value,na.rm = T), 2),
            "Mean" = round(mean(value, na.rm = T), 2),
            "Median" = round(median(value, na.rm = T), 2),
            "Standard Deviation" = round(sd(value, na.rm = T), 2))
```

```{r cal_table, results='asis'}
  kable(summ_cal)
```


# Choptank

```{r choptank_data, include=FALSE}
summ_chop <- wi %>%
  filter(watershed == "choptank") %>%
  filter(!variable %in% index_vars) %>%
  filter(!stringr::str_detect(variable, "_old")) %>%
  group_by(variable) %>%
  summarise("N" = n(),
            "Minimum" = round(min(value,na.rm = T), 2),
            "Maximum" = round(max(value,na.rm = T), 2),
            "Mean" = round(mean(value, na.rm = T), 2),
            "Median" = round(median(value, na.rm = T), 2),
            "Standard Deviation" = round(sd(value, na.rm = T), 2))
```

```{r chop_table, results='asis'}
  kable(summ_chop)
```


# East Fork Little Miami River

```{r eflmr_data, include=FALSE}
summ_eflmr <- wi %>%
  filter(watershed == "east fork little miami river") %>%
  filter(!variable %in% index_vars) %>%
  filter(!stringr::str_detect(variable, "_old")) %>%
  group_by(variable) %>%
  summarise("N" = n(),
            "Minimum" = round(min(value,na.rm = T), 2),
            "Maximum" = round(max(value,na.rm = T), 2),
            "Mean" = round(mean(value, na.rm = T), 2),
            "Median" = round(median(value, na.rm = T), 2),
            "Standard Deviation" = round(sd(value, na.rm = T), 2))
```

```{r eflmr_table, results='asis'}
  kable(summ_eflmr)
```


# Narragansett Bay

```{r nb_data, include=FALSE}
summ_nb <- wi %>%
  filter(watershed == "narragansett bay") %>%
  filter(!variable %in% index_vars) %>%
  filter(!stringr::str_detect(variable, "_old")) %>%
  group_by(variable) %>%
  summarise("N" = n(),
            "Minimum" = round(min(value,na.rm = T), 2),
            "Maximum" = round(max(value,na.rm = T), 2),
            "Mean" = round(mean(value, na.rm = T), 2),
            "Median" = round(median(value, na.rm = T), 2),
            "Standard Deviation" = round(sd(value, na.rm = T), 2))
```

```{r nb_table, results='asis'}
  kable(summ_nb)
```